name: build
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: test
      run: make test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: build
      run: make
    - name: resume
      run: make resume
    - name: html2pdf
      uses: connormckelvey/html2pdf-action@v3.0.1
      with:
        html: resume/dist/resume.html
    - name: Archive resume
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: |
          resume/dist/resume.html
          resume/dist/resume.html.pdf
