name: main
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: test
      run: make test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: build
      run: make
    - name: resume
      run: make resume
  
  
