name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
            make build
            cp build/resume.docx build/connor_mckelvey_resume.docx
            cp build/resume.pdf build/connor_mckelvey_resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/connor_mckelvey_resume.docx
            build/connor_mckelvey_resume.pdf
