name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: true
      - name: Deps
        run: go install github.com/connormckelvey/tmplrun/cmd/tmplrun@v0.1.0
      - name: Build
        run: |
            make build
            cp build/resume.docx build/connor_mckelvey_resume.docx
            cp build/resume.pdf build/connor_mckelvey_resume.pdf
            cp build/resume.html build/connor_mckelvey_resume.html
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/connor_mckelvey_resume.docx
            build/connor_mckelvey_resume.pdf
            build/connor_mckelvey_resume.html
