name: release
on:
  push:
    tags:
      - v*
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download resume artifact
        uses: actions/download-artifact@v3
        with:
          name: resume
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload HTML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: resume.html
          asset_name: resume.html
          asset_content_type: text/html
      - name: Upload PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: resume.html.pdf
          asset_name: resume.html.pdf
          asset_content_type: application/pdf
      - name: Publish to website
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
        run: |
          sudo apt-get install -y awscli
          aws s3 cp resume.html s3://www.connormckelvey.com/resume.html --acl public-read
          aws s3 cp resume.html.pdf s3://www.connormckelvey.com/resume.pdf --acl public-read
  
  
