name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: on

permissions:
  contents: read

jobs:
  golangci-lint:
    permissions:
      contents: read
      pull-requests: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
          check-latest: true
          cache: true
      - run: make fmt
      - uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: --verbose

  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        go:
        - 21
        - 22
    name: '${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.${{ matrix.go }}.x
        cache: true
    - run: make test